# Generated by Django 5.2.3 on 2025-07-13 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Digits only. Spaces and dashes are allowed.', max_length=25, validators=[django.core.validators.RegexValidator(message='Card number can only contain digits, spaces, and hyphens.', regex='^[\\d\\s-]+$')])),
                ('exp_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'credit_card',
                'unique_together': {('card_number', 'exp_month', 'exp_year')},
            },
        ),
    ]
