# Generated by Django 5.2.3 on 2025-07-11 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Only numbers, no spaces.', max_length=19, validators=[django.core.validators.RegexValidator('^\\d{13,19}$', message='The card number must contain only digits (13-19).')])),
                ('cvc', models.CharField(help_text='3 or 4 numbers, depending on the circuit.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3,4}$', message='CVC must contain 3 or 4 numbers.')])),
                ('exp_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(12)])),
                ('exp_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'db_table': 'credit_card',
                'unique_together': {('card_number', 'cvc', 'exp_month', 'exp_year')},
            },
        ),
    ]
