# Generated by Django 5.2.3 on 2025-07-11 17:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Type of sensor',
                'verbose_name_plural': 'Types of sensors',
                'db_table': 'sensor_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True, max_length=2000)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('types', models.ManyToManyField(related_name='sensors', to='sensor.sensortype')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=200)),
                ('is_registered', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=30)),
                ('label', models.CharField(blank=True, max_length=70, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorItems', to='order.order')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorItems', to='sensor.sensor')),
            ],
            options={
                'verbose_name': 'SensorItem',
                'verbose_name_plural': 'SensorItems',
                'db_table': 'sensor_item',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('id', 'sensor'), name='unique_sensoritem_id_sensor')],
            },
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative'),
        ),
    ]
