# Generated by Django 5.2.4 on 2025-07-25 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('order', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='images/sensors/na.png', null=True, upload_to='images/sensors')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Type of sensor',
                'verbose_name_plural': 'Types of sensors',
                'db_table': 'sensor_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=600)),
                ('is_registered', models.BooleanField(default=False)),
                ('api_key', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=70, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensorItems', to='user.customer')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorItems', to='group.group')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensorItems', to='order.order')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensorItems', to='sensor.sensor')),
            ],
            options={
                'verbose_name': 'SensorItem',
                'verbose_name_plural': 'SensorItems',
                'db_table': 'sensor_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sensorItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Data', to='sensor.sensoritem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SensorsData', to='sensor.sensortype')),
            ],
            options={
                'verbose_name': 'Sensor data',
                'verbose_name_plural': 'Data from Sensors',
                'db_table': 'sensor_data',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='types',
            field=models.ManyToManyField(related_name='sensors', to='sensor.sensortype'),
        ),
        migrations.AddConstraint(
            model_name='sensoritem',
            constraint=models.UniqueConstraint(fields=('id', 'sensor'), name='unique_sensoritem_id_sensor'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative'),
        ),
    ]
