# Generated by Django 5.2.4 on 2025-07-24 08:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sensorItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Data', to='sensor.sensoritem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SensorsData', to='sensor.sensortype')),
            ],
            options={
                'verbose_name': 'Sensor data',
                'verbose_name_plural': 'Data from Sensors',
                'db_table': 'sensor_data',
                'ordering': ['id'],
            },
        ),
    ]
