# Generated by Django 5.2.3 on 2025-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoritem',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
