# Generated by Django 5.2.4 on 2025-07-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
