# Generated by Django 5.2.4 on 2025-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
