# Generated by Django 5.2.4 on 2025-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensor_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='image',
            field=models.ImageField(blank=True, default='images/sensors/na.png', null=True, upload_to='images/sensors'),
        ),
    ]
