# Generated by Django 5.2.4 on 2025-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_sensor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoritem',
            name='registration_code',
            field=models.CharField(max_length=600),
        ),
    ]
