# Generated by Django 5.2.4 on 2025-07-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alter_sensoritem_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoritem',
            name='api_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sensoritem',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
