# Generated by Django 5.2.4 on 2025-07-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='authorType',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Staff', 'Staff')], max_length=10, null=True),
        ),
    ]
