# Generated by Django 5.2.4 on 2025-07-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketmessage_authortype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='messages',
            field=models.TextField(max_length=2000),
        ),
    ]
