# Generated by Django 5.2.4 on 2025-07-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticketmessage_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmessage',
            old_name='messages',
            new_name='message',
        ),
    ]
