# Generated by Django 5.2.3 on 2025-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Awaiting Payment'), (3, 'Awaiting Shipment'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Shipped')], default=1),
        ),
    ]
