# Generated by Django 5.2.3 on 2025-07-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
